CREATE TABLE "contries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "destinations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "destinations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL,
	"image_url" text NOT NULL,
	"is_popular" boolean NOT NULL,
	"country_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "faqs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faqs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)
);
--> statement-breakpoint
CREATE TABLE "trips" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trips_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title_en" text NOT NULL,
	"title_ru" text NOT NULL,
	"description_en" text NOT NULL,
	"description_ru" text NOT NULL,
	"long_description_en" text NOT NULL,
	"long_description_ru" text NOT NULL,
	"assets_urls" text[] NOT NULL,
	"travel_time" time NOT NULL,
	"destination_id" integer NOT NULL,
	"trip_price_in_cents" integer NOT NULL,
	"is_available" boolean NOT NULL,
	"is_featured" boolean NOT NULL,
	"bookings_limit_count" integer NOT NULL,
	"duration" text NOT NULL,
	"available_days" text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "trip_bookings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_bookings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"price_in_cents" integer NOT NULL,
	"trip_id" integer NOT NULL,
	"trip_start_time" timestamp with time zone,
	"status" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "trip_features" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_features_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content_en" text NOT NULL,
	"content_ru" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trip_to_feature" (
	"trip_id" integer NOT NULL,
	"feature_id" integer NOT NULL,
	CONSTRAINT "trip_to_feature_trip_id_feature_id_pk" PRIMARY KEY("trip_id","feature_id")
);
--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)
);
--> statement-breakpoint
ALTER TABLE "destinations" ADD CONSTRAINT "destinations_country_id_contries_id_fk" FOREIGN KEY ("country_id") REFERENCES "public"."contries"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trips" ADD CONSTRAINT "trips_destination_id_destinations_id_fk" FOREIGN KEY ("destination_id") REFERENCES "public"."destinations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_bookings" ADD CONSTRAINT "trip_bookings_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_to_feature" ADD CONSTRAINT "trip_to_feature_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_to_feature" ADD CONSTRAINT "trip_to_feature_feature_id_trip_features_id_fk" FOREIGN KEY ("feature_id") REFERENCES "public"."trip_features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "trip_bookings" USING btree ("user_id");