CREATE TABLE "trip_to_trip_type" (
	"trip_id" integer NOT NULL,
	"trip_type_id" integer NOT NULL,
	CONSTRAINT "trip_to_trip_type_trip_id_trip_type_id_pk" PRIMARY KEY("trip_id","trip_type_id")
);
--> statement-breakpoint
CREATE TABLE "trip_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trip_bookings" ADD COLUMN "user_email" text NOT NULL;--> statement-breakpoint
ALTER TABLE "trip_to_trip_type" ADD CONSTRAINT "trip_to_trip_type_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_to_trip_type" ADD CONSTRAINT "trip_to_trip_type_trip_type_id_trip_type_id_fk" FOREIGN KEY ("trip_type_id") REFERENCES "public"."trip_type"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trips" DROP COLUMN "trip_type";